version: "3"

services:
  database:
    restart: unless-stopped
    image: postgis/postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geoapp
    ports:
      - "5432:5432"
